### ISSUE TITLE
Бесполезный бот

### ISSUE THREAD

**Issue by p4vook** [AlpacaGang/PublishBot#1]
Этот бот никому не нужен. Зачем этот бот? Непонятно...

**Comment by vanutp** [comment]
@pavel-the-best Ты додик штоле?

**Comment by p4vook** [comment]
Прошу вас, не оскорбляйте меня. Зачем нужен этот бот? Непонятно. Поэтому этот бот не нужен. А значит, его нужно УДАЛИТЬ!

**Comment by vanutp** [comment]
@pavel-the-best .....
