### ISSUE TITLE
gitlab.sh - hardcoded GitLab instance URL

### ISSUE THREAD

**Issue by ntoneee** [AlpacaGang/PublishBot#4]
Hardcoded git.vanutp.dev makes originalTM gitlab.sh usable only on one mentioned above instance, but the CI script is unusable in case gitlab.com or other Gitlab instances host the repository.

**Comment by vanutp** [comment]
да просто remove его надо
и migrate to webhooks

**Comment by ntoneee** [comment]
На Русском: 🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺

Так как в gitlab.sh адрес инстанса (git.vanutp.dev) захардкожен, то вышеупомянутый скрипт нельзя юзать на других инстансах гитлаба - например, gitlab.com.

**Comment by FedShat** [comment]
Брать из енва INSTANCE и экспортить в .yml при запуске

**Comment by ntoneee** [comment]
> Брать из енва INSTANCE и экспортить в .yml при запуске

гении зачастую становятся отвергнутыми обществом

**Comment by ntoneee** [comment]
> да просто remove его надо
> и migrate to webhooks

where do we use gitlab.sh except t.me/FindNewBot?

**Comment by ntoneee** [comment]
Closed in commit 0554211
